export const FETCH_ALL_DOGS = 'FETCH_ALL_DOGS';
export const FETCH_DOGS_BY_NAME = 'FETCH_DOGS_BY_NAME';
export const SELECT_PAGE = 'SELECT_PAGE';
export const FETCH_ALL_TEMPERAMENTS = 'FETCH_ALL_TEMPERAMENTS';
export const UPDATE_DOGS_CONTAINER = 'UPDATE_DOGS_CONTAINER';
export const FETCH_DOG_BY_ID = 'FETCH_DOG_BY_ID';
export const SEND_DOG_TO_DB = 'SEND_DOG_TO_DB';